spring:
  session:
    store-type: redis
zuul: 
  retryable: true
  routes:
    order-management-ms: /order-management/**
sensitiveHeaders: Authorization, Set-Cookie
security:
  user:
    name: gateway
    password: password

